### ISSUE TITLE
Improve guides

### ISSUE THREAD

**Issue by PierreBresson** [NMF-earth/nmf-app#199]
- [x] Fix wrong alignment
- [x] Open link in the browser when clicking on one
- [x] Increase font size

<img width="499" alt="Screenshot 2020-10-10 at 21 07 13" src="https://user-images.githubusercontent.com/8709134/95663148-e43bce00-0b3c-11eb-85bd-36a01839ae61.png">

**Comment by BatDroid** [comment]
I'm on it. just wondering if I should make one pr per to do or one for all

**Comment by BatDroid** [comment]
I just added all in one pr so that It won't be labeled as spam sth

**Comment by PierreBresson** [comment]
@BatDroid I won't close this ticket for now because the alignment issue persist if I run `node scripts/generate-guides.js`

**Comment by BatDroid** [comment]
> @BatDroid I won't close this ticket for now because the alignment issue persist if I run `node scripts/generate-guides.js`

I couldn't find the way the guides were generated. I just changed the generated file. I'll fix it in a new PR. btw, Though I could see it in the docs that you've mentioned about it, I believe it would be good to have a comment line like this in the generated file.
/* this is a generated file. change the md files. modify the md files & run the node script/... to see the result  */

**Comment by BatDroid** [comment]
> @BatDroid I won't close this ticket for now because the alignment issue persist if I run `node scripts/generate-guides.js`
I face this error when I run the mentioned `generate-guides.js` . doesn't it happen to you?
![Uploading Simulator Screen Shot - iPhone 11 - 2020-10-12 at 00.11.32.png…]()

**Comment by BatDroid** [comment]
> @BatDroid I won't close this ticket for now because the alignment issue persist if I run `node scripts/generate-guides.js`

I face this error when I run the mentioned generate-guides.js . doesn't it happen to you?
![Simulator Screen Shot - iPhone 11 - 2020-10-12 at 00 11 32](https://user-images.githubusercontent.com/10198892/95690196-b9c44080-0c22-11eb-904f-e8beaa852a88.png)

**Comment by PierreBresson** [comment]
@BatDroid humm nope, I'm on latest master and `node scripts/generate-guides.js` works well for me.

**Comment by BatDroid** [comment]
> @BatDroid humm nope, I'm on latest master and `node scripts/generate-guides.js` works well for me.
Sorry, I tried everything and I still face the error. I even cloned the main repo and ran it there and this error happens after I run the script.I couldn't find the source of my problem and maybe it is related to my node version which is `v14.4.0`. I'll work on other issues.
Just for who ever going to to this. It should be related to `internet-browsing-impact.md` because the other guides work without any problem. what I did on the generated file was exactly the same. removing the generated `p` tags that doesn't exists in the others.

**Comment by BatDroid** [comment]
> @BatDroid humm nope, I'm on latest master and `node scripts/generate-guides.js` works well for me.

Sorry, I tried everything and I still face the error. I even cloned the main repo and ran it there and this error happens after I run the script.I couldn't find the source of my problem and maybe it is related to my node version which is v14.4.0. I'll work on other issues.
Just for who ever going to to this. It should be related to internet-browsing-impact.md because the other guides work without any problem. what I did on the generated file was exactly the same. removing the generated p tags that doesn't exists in the others.

**Comment by hb2708** [comment]
@PierreBresson I was looking into this now. But when i run `node scripts/generate-guides.js` it does nothing. as per the script i see it should log `"Wrote guides.json"` at the end. So to debug that i added console log for `files` but it prints an empty array

**Comment by PierreBresson** [comment]
@hb2708 I think it's because you need to run the script within the folder if I remember well. So `cd scripts` and then `node generate-guides.js`... yes, some improvement is needed ;)

**Comment by hb2708** [comment]
@PierreBresson Nope does not work 
`.readdirSync(`${process.env.PWD}/assets/images/guide`)` fails with following error 

Error: ENOENT: no such file or directory, scandir '/Users/harshalbhavsar/Documents/Harshal/nmf-app/scripts/assets/images/guide'

**Comment by hb2708** [comment]
@PierreBresson Does this looks good?

1. Fixed the alignment issue By changing the .md File.
2. Made the hyperlink 1,3 Bold same as the 2nd one

Before                            |  After
:----------------------:|:-------------------------:
![Before](https://user-images.githubusercontent.com/13498448/97778242-e54aa300-1bb0-11eb-882c-56b914c18700.jpeg)  |  ![After](https://user-images.githubusercontent.com/13498448/97778236-e085ef00-1bb0-11eb-9058-47a5860a7285.PNG)

**Comment by hb2708** [comment]
@PierreBresson let me know if the above works for you then will create a pr. Thanks

**Comment by PierreBresson** [comment]
@hb2708 thanks for sharing the way to resolve the issue, I've pushed a temporary [fix](https://github.com/NMF-earth/nmf-app/commit/a32dc9adc900803964ec7964d299d04a6a9a87f1) and open a [ticket](https://github.com/NMF-earth/nmf-app/issues/239) for a long term solution

**Comment by hb2708** [comment]
@PierreBresson happy to help
