### ISSUE TITLE
Fix DatePicker in the "AddEmission" Page

### ISSUE THREAD

**Issue by adamfitzgibbon** [NMF-earth/nmf-app#219]
I noticed while testing on iPhone that the DatePicker component does not render correctly. The modal shows up and I can hear it moving when I swipe over it, but the modal is visually blank. I did not attempt to recreate on other devices but that would be a good first step.

**Comment by PierreBresson** [comment]
I don't have an iPhone with me at the moment and it's working well on the simulator. Can you add a screenshot ? I will probably do an OTA update because of this issue I think
<img width="502" alt="Screenshot 2020-10-18 at 17 47 58" src="https://user-images.githubusercontent.com/8709134/96373015-2206ab00-116a-11eb-9683-4157c6ec74dd.png">

**Comment by adamfitzgibbon** [comment]
Sure, this is on an iPhone 11 Pro for the record. 
![Uploading DBC9BDF0-0799-467B-8B47-4F420F0B86C9.png…]()

**Comment by hb2708** [comment]
@adamfitzgibbon @PierreBresson Should be fixed now.

**Comment by hb2708** [comment]
@PierreBresson can assign it also?
