### ISSUE TITLE
Feature: I want to implement app deeplink to open app from browser link with auth code, for that in i need to add configuration in androidmanifest.xml under android folder   

### ISSUE THREAD

**Issue by SAISUDHEERREDDY** [NMF-earth/nmf-app#372]
#### Summary
I want to implement app deep-link to open the app from the browser link with auth code, for that in I need to add configuration in androidmanifest.xml under the android folder

But I was unable to find the Android project in the NMF-earth project. where can add androidmanifest.xml?

Here is the code I want to add
`<activity  
    <intent-filter>
        <action android:name="android.intent.action.VIEW" />
        <category android:name="android.intent.category.DEFAULT" />
        <category android:name="android.intent.category.BROWSABLE" />
        <data android:scheme="http" />
        <data android:scheme="https" />
        <data android:host="www.example.com" />
    </intent-filter>
</activity> 
`
#### Proposed feature

Please find below documentation of what I want to achieve
https://reactnavigation.org/docs/deep-linking/

#### To Do List 
Checklist, nice to have, but not mandatory

- [ ] Code
- [ ] Tests
- [ ] README.md updated

**Comment by PierreBresson** [comment]
Hi @SAISUDHEERREDDY 
It's normal that you can't find the android manifest since the app is using Expo framework on top of React Native. If you want to implement deep link, [here is the documentation](https://github.com/NMF-earth/nmf-app/issues/101) for expo.
This task has been approved, [you can find it here](https://github.com/NMF-earth/nmf-app/issues/101) so I will close this one as it is a duplicate.
Let me know if you need help ;)
